# Generated by Django 4.1.5 on 2023-01-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountability_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="post",
            name="post_text",
            field=models.TextField(max_length=278),
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="accountability_app.tag"
            ),
        ),
    ]
