# Generated by Django 4.1.5 on 2023-01-22 09:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accountability_app", "0004_alter_post_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="date published"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(to="accountability_app.tag"),
        ),
        migrations.AlterUniqueTogether(
            name="post",
            unique_together={("author", "post_text")},
        ),
    ]
